services:
  inventory-app:
    image: ghcr.io/florianwenzelworms/inventar-neu:latest
    container_name: it-inventur
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - TZ=Europe/Berlin